spring.application.name=orchestrator-service
server.port=8080

spring.kafka.bootstrap-servers=${KAFKA_BROKER:localhost:9092}
spring.kafka.consumer.group-id=orchestrator-group
spring.kafka.consumer.auto-offset-reset=latest

kafka.topic.orchestrator=orchestrator
kafka.topic.finish-success=finish-success
kafka.topic.finish-fail=finish-fail
kafka.topic.notify-ending=notify-ending
logging.level.org.apache.kafka=OFF