services:

  order-db:
    image: mongo:latest
    container_name: order-db
    restart: always
    networks:
      - orchestrator-saga
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10

  product-db:
    container_name: product-db
    image: postgres:latest
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - orchestrator-saga
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d product-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  payment-db:
    container_name: payment-db
    image: postgres:latest
    environment:
      POSTGRES_DB: payment-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - orchestrator-saga
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d payment-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  inventory-db:
    container_name: inventory-db
    image: postgres:latest
    environment:
      POSTGRES_DB: inventory-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - orchestrator-saga
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory-db"]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - orchestrator-saga
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data


  redpanda-console:
    container_name: redpanda
    image: docker.redpanda.com/redpandadata/console:v2.3.8
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "8081:8080"
    networks:
      - orchestrator-saga
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:29092"]
    depends_on:
      - "kafka"

  order-service:
    #container_name: order-service
    build: './order-service'
    depends_on:
      kafka:
        condition: service_started
      order-db:
        condition: service_healthy
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
      - MONGO_URI=mongodb://admin:123456@order-db:27017/admin
    #ports:
     # - "3000:3000"
    expose:
      - "3000"
    deploy:
      replicas: 3

  orchestrator-service:
    container_name: orchestrator-service
    build: './orchestrator-service'
    depends_on:
      kafka:
        condition: service_started
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
    ports:
      - "8080:8080"

  product-service:
    container_name: product-service
    build: './product-service'
    depends_on:
      kafka:
        condition: service_started
      product-db:
        condition: service_healthy
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=product-db
      - DB_PORT=5432
      - DB_NAME=product-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8090:8090"

  payment-service:
    container_name: payment-service
    build: './payment-service'
    depends_on:
      kafka:
        condition: service_started
      payment-db:
        condition: service_healthy
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=payment-db
      - DB_PORT=5432
      - DB_NAME=payment-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8091:8091"

  inventory-service:
    container_name: inventory-service
    build: './inventory-service'
    depends_on:
      kafka:
        condition: service_started
      inventory-db:
        condition: service_healthy
    networks:
      - orchestrator-saga
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=inventory-db
      - DB_PORT=5432
      - DB_NAME=inventory-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8092:8092"

  order-lb:
    image: nginx:alpine
    container_name: order-lb
    depends_on:
      - order-service
    networks:
      - orchestrator-saga
    ports:
      - "3000:80"     # o host continua acessando em localhost:3000, agora via LB
    volumes:
      - ./loadbalance/nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  orchestrator-saga:
    driver: bridge