spring.application.name=order-service
server.port=3000

spring.mongodb.uri=${MONGO_URI:mongodb://admin:123456@localhost:27017/admin}

spring.kafka.bootstrap-servers=${KAFKA_BROKER:localhost:9092}
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.auto-offset-reset=latest

kafka.topic.notify-ending=notify-ending
kafka.topic.start-saga=start-saga
logging.level.org.apache.kafka=OFF


management.endpoints.web.exposure.include=health,info,metrics,prometheus,logs
management.tracing.propagation.type=W3C
management.tracing.opentelemetry.tracing.exporter=otlp
management.otlp.metrics.export.exporter=otlp
management.otlp.metrics.export.url=http://otel-collector:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://otel-collector:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://otel-collector:4318/v1/logs
management.tracing.enabled=true
management.include-each-metric-with-tags=true
management.tracing.sampling.probability=1.0

spring.kafka.listener.observation-enabled=true
spring.kafka.template.observation-enabled=true

logging.level.io.opentelemetry=DEBUG

logging.pattern.level=%5p [${spring.application.name},%X{traceId},%X{spanId}]
