spring.application.name=order-service
server.port=3000

spring.mongodb.uri=${MONGO_URI:mongodb://admin:123456@localhost:27017}

spring.kafka.bootstrap-servers=${KAFKA_BROKER:localhost:9092}
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.auto-offset-reset=latest

kafka.topic.notify-ending=notify-ending
kafka.topic.start-saga=start-saga
logging.level.org.apache.kafka=OFF
