spring.application.name=product-service
server.port=8090

spring.kafka.bootstrap-servers=${KAFKA_BROKER:localhost:9092}
spring.kafka.consumer.group-id=product-group
spring.kafka.consumer.auto-offset-reset=latest

kafka.topic.product-validation-success=product-validation-success
kafka.topic.product-validation-fail=product-validation-fail
kafka.topic.orchestrator=orchestrator
logging.level.org.apache.kafka=OFF

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:product-db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

