spring.application.name=inventory-service
server.port=8092

spring.kafka.bootstrap-servers=${KAFKA_BROKER:localhost:9092}
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=latest

kafka.topic.inventory-success=inventory-success
kafka.topic.inventory-fail=inventory-fail
kafka.topic.orchestrator=orchestrator
logging.level.org.apache.kafka=INFO


spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:inventory-db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


management.endpoints.web.exposure.include=health,info,metrics,prometheus,logs
management.tracing.propagation.type=W3C
management.tracing.opentelemetry.tracing.exporter=otlp
management.otlp.metrics.export.exporter=otlp
management.otlp.metrics.export.url=http://otel-collector:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://otel-collector:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://otel-collector:4318/v1/logs
management.tracing.enabled=true
management.include-each-metric-with-tags=true
management.tracing.sampling.probability=1.0

spring.kafka.listener.observation-enabled=true
spring.kafka.template.observation-enabled=true

logging.level.io.opentelemetry=DEBUG

logging.pattern.level=%5p [${spring.application.name},%X{traceId},%X{spanId}]
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.data.repository.core=DEBUG
logging.level.org.hibernate.SQL=DEBUG